#!/usr/bin/env bash

tempDir=/tmp/yabai-tiling-floating-toggle
[ -d $tempDir ] && rm -rf $tempDir
mkdir $tempDir

set -x

declare -A color
color["focused"]="0xF0392d45"
color["normal"]="0x00000000"
color["preselect"]="0x00000000"
color["resize"]="0xFFFF00FF"

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout                      bsp

yabai -m config top_padding                 15
yabai -m config bottom_padding              15
yabai -m config left_padding                25
yabai -m config right_padding               25
yabai -m config window_gap                  15

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         on

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config window_border               off
yabai -m config window_border_width         4
yabai -m config active_window_border_color  "${color["focused"]}"
yabai -m config normal_window_border_color  "none"
yabai -m config insert_feedback_color       "${color["preselect"]}"

yabai -m config active_window_opacity       0.80
yabai -m config normal_window_opacity       1.0
yabai -m config split_ratio                 0.50

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
set +x
printf "yabai: configuration loaded...\\n"
